### ISSUE TITLE
Center the selected search result node

### ISSUE THREAD

**Issue by miloyip** [miloyip/gamextech#4]
Suggested in https://github.com/miloyip/gamextech/issues/1#issuecomment-783218283

**Comment by miloyip** [comment]
@zwcloud I have been thinking about how to implement this. But when the search result node is added to the graph, it will be moving for awhile (via the d3 force module). Centering it may cause the whole screen shaking.

**Comment by zwcloud** [comment]
> @zwcloud I have been thinking about how to implement this. But when the search result node is added to the graph, it will be moving for awhile (via the d3 force module). Centering it may cause the whole screen shaking.

I'm not familar with d3. It might provide some functionality like smoothly translation over time? Also if the centering operation takes sometime, we can force stop the movement if any user input(dragging) is received during the centering operation.

Imitating mouse dragging might be another alternative.
