### ISSUE TITLE
interested in some teches that i don't know.

### ISSUE THREAD

**Issue by jcyuan** [miloyip/gamextech#5]
hi there, great repo, thanks so much for your effort.
is it possible to submit what game tech i wanna know here?
if so:

1, which is the best way to communicate with the FSM? IMO some people handle all user input and switch the current state of the machine directly in each states. and some FSM uses table look up tech to handle state switching etc. i'm not quit clear on this, i'm wondering is there a suggested way to handle user input to switch the FSM?

2, flexible BUFF system
    
3, damage calculating system (with buff system), and, maybe this will affects the FSM system too? for example when the character hurts this will switch the FSM to hurt state?

4, animation system, how to manually apply motion and mix it with the existing root motion.

actually, the basic knowledge is clear, but when you apply them in your game, those problems appear. just wanna know some flexible idea on them.
thank you!

**Comment by miloyip** [comment]
I think this usage may not be suitable as question/answer platform such as https://gamedev.stackexchange.com/ .
But if you research and find related good articles, you may try to organize them and put into this database.
For 2/3, BUFF system should be mentioned in some articles or presentations, which may be put in the gameplay part.
For 4, There is various common types of blending methods, which we can add into the database.

**Comment by jcyuan** [comment]
got it!
for 1, will do, if find something good enough i'll try to do so as you mentioned.
 thanks so much.  👍
